const stateFIPS: Record<string, string> = {
  'alabama': "01",
  'alaska': "02",
  'arizona': "04",
  'arkansas': "05",
  'california': "06",
  'colorado': "08",
  'connecticut': "09",
  'delaware': "10",
  'district of columbia': "10",
  'florida': "12",
  'georgia': "13",
  'hawaii': "15",
  'idaho': "16",
  'illinois': "17",
  'indiana': "18",
  'iowa': "19",
  'kansas': "20",
  'kentucky': "21",
  'louisiana': "22",
  'maine': "23",
  'maryland': "24",
  'massachusetts': "25",
  'michigan': "26",
  'minnesota': "27",
  'mississippi': "28",
  'missouri': "29",
  'montana': "30",
  'nebraska': "31",
  'nevada': "32",
  'new hampshire': "33",
  'new jersey': "34",
  'new mexico': "35",
  'new york': "36",
  'north carolina': "37",
  'north dakota': "38",
  'ohio': "39",
  'oklahoma': "40",
  'oregon': "41",
  'pennsylvania': "42",
  'rhode island': "44",
  'south carolina': "45",
  'south dakota': "46",
  'tennessee': "47",
  'texas': "48",
  'utah': "49",
  'vermont': "50",
  'virginia': "51",
  'washington': "53",
  'west virginia': "54",
  'wisconsin': "55",
  'wyoming': "56",
  'american samoa': "60",
  'guam': "66",
  'northern mariana islands': "69",
  'puerto rico': "72",
  'virgin islands': "78",
  'non-us resident': "NONRESIDENT"
}

export function getFIPSByStateName(stateName: string): string {
  return stateFIPS[stateName.toLowerCase()];
}

export const parseNumber = (num: number | string) => {
  if (typeof num === "number") return num;
  return parseInt(num.replace(",", ""));
};